void rapidityClosure() {
  TFile *f_ele_mc   = TFile::Open("/data/t3home000/dhsu/root/corrected/DYJetsToLL_BaselineToMedium_ScaleSmearCorrections_PtInclusiveNLO_electronTnP.root");
  TFile *f_ele_data = TFile::Open("/data/t3home000/dhsu/root/corrected/SingleElectron2016_BaselineToMedium_ScaleSmearCorrections_electronTnP.root");
  TFile *f_mu_mc    = TFile::Open("/data/t3home000/dhsu/root/corrected/DYJetsToLL_BaselineToMedium_RochesterCorrections_PtInclusiveNLO_muonTnP.root");
  TFile *f_mu_data  = TFile::Open("/data/t3home000/dhsu/root/corrected/SingleMuon2016_BaselineToMedium_RochesterCorrections_muonTnP.root");

  TH1D *h_mu_mc    = new TH1D("h_mu_mc"   , "h_mu_mc"   ,24,0,2.4); 
  TH1D *h_mu_data  = new TH1D("h_mu_data" , "h_mu_data" ,24,0,2.4); 
  
  TCut mcSelection; TTree *events; TH1D *hDTotalMCWeight; TCut dataSelection;
  f_ele_mc->cd(); events=(TTree*)f_ele_mc->Get("events"); hDTotalMCWeight=(TH1D*)f_ele_mc->Get("hDTotalMCWeight");
  TH1D *h_ele_mc   = new TH1D("h_ele_mc"  , "h_ele_mc"  ,24,0,2.4); 
  mcSelection=Form("scale1fb*%f*(tag.Pt()>25. && probe.Pt()>25. && mass>76.1876 && mass<=106.1876 && (probe.Eta()>-2.5 && probe.Eta()<2.5) && (tag.Eta()>-2.5 && tag.Eta()<2.5) && pass==1 && qtag+qprobe==0)",.0359*6025.2/hDTotalMCWeight->Integral());
  events->Draw("TMath::Abs(0.5*TMath::Log((tag.E()+probe.E()+tag.Pz()+probe.Pz())/(tag.E()+probe.E()-tag.Pz()-probe.Pz())))>>+h_ele_mc",mcSelection,"goff");
  f_ele_data->cd(); events=(TTree*)f_ele_data->Get("events"); hDTotalMCWeight=(TH1D*)f_ele_data->Get("hDTotalMCWeight");
  TH1D *h_ele_data = new TH1D("h_ele_data", "h_ele_data",24,0,2.4); 
  dataSelection="(tag.Pt()>25. && probe.Pt()>25. && mass>76.1876 && mass<=106.1876 && (probe.Eta()>-2.5 && probe.Eta()<2.5) && (tag.Eta()>-2.5 && tag.Eta()<2.5) && pass==1 && qtag+qprobe==0)";
  events->Draw("TMath::Abs(0.5*TMath::Log((tag.E()+probe.E()+tag.Pz()+probe.Pz())/(tag.E()+probe.E()-tag.Pz()-probe.Pz())))>>+h_ele_data",dataSelection,"goff");
  h_ele_mc->Draw("HIST");
  h_ele_data->Draw("P E0 X0 SAME");

/*
  // Draw fit
  gStyle->SetOptStat(0);
  TCanvas *canvas=new TCanvas(Form("c_%s",histName.c_str()), Form("c_%s",histName.c_str()),600,480);
  canvas->SetTopMargin(0.0); 
  canvas->SetBottomMargin(0); 
  canvas->SetRightMargin(0.02);
  TPad *pad1 = new TPad("pad1", "pad1", 0, 0.3, 1.,1);
  pad1->SetTopMargin(0.1);
  pad1->SetLeftMargin(0.15);
  pad1->SetRightMargin(0.04);
  pad1->SetBottomMargin(0.03); 
  pad1->SetGridx();         
  pad1->Draw();             
  pad1->cd();              
  RooPlot *frame = m.frame(Bins(30));
  plotTitle.ReplaceAll("~"," ");
  frame->SetTitle(plotTitle!=""?plotTitle:histName);
  frame->GetXaxis()->SetLabelSize(0);
  frame->GetXaxis()->SetTitle("");
  frame->GetYaxis()->SetTitleOffset(1.2);
  frame->GetYaxis()->SetTitleSize(0.05);
  frame->GetYaxis()->SetTitle(Form("Events / %.1f GeV",dataHist->GetBinWidth(1)));
  frame->GetYaxis()->SetLabelSize(0.05);
  //dataRDH->plotOn(frame,MarkerStyle(kFullCircle),MarkerSize(0.5),DrawOption("ZP")); 
  totalPdf->plotOn(frame, Name("sigPdfLine"), LineStyle(kSolid), LineColor(kViolet-4), DrawOption("l"), Normalization(Ntotal.getVal(),RooAbsReal::NumEvent));
  totalPdf->plotOn(frame, Name("bkgPdfLine"), Components("bkgModel"),LineColor(kCyan-6),LineStyle(kDashed),DrawOption("l"),Normalization(Ntotal.getVal(),RooAbsReal::NumEvent));
  totalPdf->plotOn(frame, Components("bkgModel"),VisualizeError(*fitResult,1,kTRUE),FillStyle(3004),FillColor(kCyan-6),Normalization(Ntotal.getVal(),RooAbsReal::NumEvent));
  //dataRDH->plotOn(frame,MarkerStyle(kFullCircle),MarkerSize(0.5),DrawOption("ZP")); 
  frame->GetYaxis()->SetRangeUser(0, 1.4*dataHist->GetBinContent(dataHist->GetMaximumBin()));
  frame->Draw();
  pdfErrorBand->SetMarkerColor(kViolet-4);
  pdfErrorBand->SetFillStyle(3254);
  pdfErrorBand->SetFillColor(kViolet-4);
  pdfErrorBand->SetLineColor(kBlack);
  pdfErrorBand->Draw("e2 same");
  dataHistWithCombErrors->SetMarkerStyle(20);
  dataHistWithCombErrors->SetMarkerSize(0.8);
  dataHistWithCombErrors->SetMarkerColor(kBlack);
  dataHistWithCombErrors->SetLineColor(kBlack);
  dataHistWithCombErrors->SetLineWidth(2);
  dataHistWithCombErrors->Draw("p e0 same");
  TLegend *legend=new TLegend(.68,.62,.95,.88);
  legend->SetFillColor(0);
  legend->AddEntry(dataHistWithCombErrors, "Data","lp");
  legend->AddEntry("sigPdfLine", sigFitterShape->plotLabel,"l");
  if(0!=sigFitterShape->templateHist) legend->AddEntry(pdfErrorBand, "MC Stat. Unc.","f");
  legend->AddEntry("bkgPdfLine", bkgFitterShape->plotLabel,"l");
  legend->Draw("same");
  //TPaveText *fitStatsPave = new TPaveText(0.68,0.3,0.94,.58, "NDC");
  TPaveText *fitStatsPave = new TPaveText(0.18,0.6,0.44,.88, "NDC");
  fitStatsPave->SetFillColor(0);
  fitStatsPave->SetBorderSize(1);
  fitStatsPave->SetTextFont(42);
  fitStatsPave->AddText(Form("%d data events",(int)Ndata));
  fitStatsPave->AddText(Form("N_{sig} %d #pm %d",(int)round(Nsig.getVal()),(int)round(sqrt(pow(Nbkg.getError(),2)+Ntotal.getVal()))));
  fitStatsPave->AddText(Form("N_{bkg} %d #pm %d",(int)round(Nbkg.getVal()),(int)round(Nbkg.getError())));
  fitStatsPave->AddText(Form("Fit prob. %3.1f%%", fitProb*100.));
  fitStatsPave->AddText(Form("EDM %3.1e", fitResult->edm()));
  fitStatsPave->Draw("SAME");
  canvas->cd();
  TPad *pad2 = new TPad("pad2", "pad2", 0, 0.05, 1, 0.3);
  pad2->SetLeftMargin(0.15);
  pad2->SetTopMargin(0);
  pad2->SetBottomMargin(0.4);
  pad2->SetRightMargin(0.04);
  pad2->SetGridx(); 
  pad2->Draw();
  pad2->cd();
  ratioErrorBand->SetTitle("");
  ratioErrorBand->GetXaxis()->SetTitleSize(0.18);
  ratioErrorBand->GetXaxis()->SetTitleOffset(1.1);
  ratioErrorBand->GetYaxis()->SetNdivisions(503);
  ratioErrorBand->GetXaxis()->SetLabelSize(0.2);
  ratioErrorBand->GetXaxis()->SetTitle("Invariant mass [GeV]");
  ratioErrorBand->GetXaxis()->SetRangeUser(fitMassLo,fitMassHi-0.01);
  ratioErrorBand->GetYaxis()->SetTitle("Data/PDF");
  ratioErrorBand->GetYaxis()->CenterTitle();
  ratioErrorBand->GetYaxis()->SetTitleOffset(0.37);
  ratioErrorBand->GetYaxis()->SetTitleSize(0.12);
  ratioErrorBand->GetYaxis()->SetLabelSize(0.15);
  ratioErrorBand->SetFillStyle(3254);
  ratioErrorBand->SetFillColor(kBlack);
  ratioErrorBand->SetMinimum(.3);
  ratioErrorBand->SetMaximum(1.7);
  ratioErrorBand->Draw("E2");
  ratioDataPdf->SetLineColor(kBlack);
  ratioDataPdf->SetMarkerStyle(20);
  ratioDataPdf->SetMarkerSize(0.8);
  ratioDataPdf->Draw("P E0 x0 SAME");
  TLine *baseline = new TLine(0,1,2.4,1);
  baseline->SetLineStyle(kSolid); baseline->Draw("SAME");
  canvas->Print(Form("%s/plots/%s.png",outputDir.c_str(),histName.c_str()));
  canvas->Print(Form("%s/plots/%s.pdf",outputDir.c_str(),histName.c_str()));
*/

}
